apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels: 
    env: production
    owner: eslam
    webserver: nginx
spec:
  containers:
    - name: nginxcontainer1
      image: nginx:1.21.3
      ports:
        - containerPort: 80 