apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
    
      command:
        - redis-server
        - /usr/local/etc/redis/redis.conf
      
      volumeMounts:
        - name: redis-config-volume
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis-config
  volumes:
    - name: redis-config-volume
      configMap:
        name: redis-configmap
        items:
          - key: redis-config
            path: redis-config