apiVersion: v1
kind: Pod
metadata:
  name: env-server-user-pod
spec:
  containers:
    - name: env-server-user-container
      image: nginx
      env:
        - name: SECRET_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: server-user
              key: username